# action.yml
name: 'Assign to One Project'
description: 'Assign new Issue or Pull Request to default project dashboard column'
inputs:
  project:  # id of input
    description: 'Assigned Project'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
